baseURL: https://nic-seo.github.io
languageCode: en-us
title: nicseo
theme: "PaperMod"
disqusShortname: nic-seo

params:
  defaultTheme: light
  comments: true

  homeInfoParams:
    Title: Welcome to my mind
    Content: Or just the tip of the iceberg

  socialIcons: # optional
    #- name: "github"
    #  url: "https://github.com/XXX"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://www.twittter.com/nic_seo_"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "nic"
  contact: "nicole@mercuryconstant.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
